### ISSUE TITLE
Bug in discard-tokens?

### ISSUE THREAD

**Issue by dgrnbrg** [pssalmeida/clj-crdt#1]
The code in `discard-tokens` looks a bit funny to me--it seems that you're doing a `conj` of a list of kv pairs into a sorted map, where I think that you want to use `into` so that those elements become the kv pairs of the map.

**Comment by pssalmeida** [comment]
Hi David,

Arghhh, only noticed this mail now, within hundreds of mailing-list
messages. Sorry. I must organize my gmail ...

Your are right. It should be "into". Which made me amazed and scared of why
should tests have worked ... and now I learned that "conj" has a funny
special behaviour for maps, which apparently also extends to seqs of
map-entries ... which makes it behave the same as "into" in this case,
which explains no problem being caused ...

Thanks for noticing it. I will change it to "into".

Regards,
Paulo

**Comment by pssalmeida** [comment]
Change done.
